<?php

return [
    [
        'nome_carta' => 'Goblin Matto',
        'costo_mana' => 1,
        'figura' => 'https://static.miraheze.org/nonciclopediawiki/thumb/9/95/Jace_Belleren.jpg/300px-Jace_Belleren.jpg',
        'tipo_carta' => 'Creatura',
        'edizione' => 'Magic 2010',
        'effetti' => 'Attacco improvviso',
        'testo' => 'I Goblin Matto sono così insensati che non possono essere addomesticati. Il loro attacco improvviso li rende comunque utili in battaglia.',
        'forza' => 2,
        'costituzione' => 1,
    ],
    [
        'nome_carta' => 'Mana del Drago',
        'costo_mana' => 0,
        'figura' => 'https://static.wikia.nocookie.net/magicthegathering/images/b/b6/Jace%2C_the_Perfected_MindART1.jpg/revision/latest?cb=20230118071808&path-prefix=it',
        'tipo_carta' => 'Artefatto',
        'edizione' => 'Dominaria',
        'effetti' => 'Aggiunge un mana di qualsiasi colore alla tua riserva di mana.',
        'testo' => 'I draghi più potenti posseggono la capacità di condensare l\'essenza del mana in perle luminose come queste.',
        'forza' => 6,
        'costituzione' => 5,
    ],
    [
        'nome_carta' => 'Contrattacco',
        'costo_mana' => 2,
        'figura' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTjQtWLCUH-DPVMhlbsZzv0wtzvOEjmXAQvQ&usqp=CAU',
        'tipo_carta' => 'Istantaneo',
        'edizione' => 'Ravnica',
        'effetti' => 'Contrattacca una creatura attaccante o bloccante bersaglio.',
        'testo' => 'Il segreto per contrastare la furia dell\'avversario è quello di aspettare il momento giusto per colpire.',
        'forza' => 4,
        'costituzione' => 3,
    ],
    [
        'nome_carta' => 'Velo di Nebbia',
        'costo_mana' => 1,
        'figura' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVf8HIp4LPIwN28O7IvNxdUWRaiXw188Y7ZP18KLWNLIheZpe8YxNeP8fEn8yaz3TIf68&usqp=CAU',
        'tipo_carta' => 'Istantaneo',
        'edizione' => 'Ixalan',
        'effetti' => 'Prevenzione  contro il prossimo danno che verrebbe inflitto a una creatura o a un planeswalker che controlli questo turno.',
        'testo' => 'Non lasciare che i tuoi nemici vedano dove ti nascondi.',
        'forza' => 9,
        'costituzione' => 2,
    ],
    [
        'nome_carta' => 'Serra Angel',
        'costo_mana' => 5,
        'figura' => 'https://i.pinimg.com/736x/7d/1f/9b/7d1f9be5c963b6ab6118058101eba37f--lich-king-death-knight.jpg',
        'tipo_carta' => 'Creatura',
        'edizione' => 'Magic 2010',
        'effetti' => 'Volare, Vigilanza',
        'testo' => 'La sua bellezza fa dimenticare la sua ferocia.',
        'forza' => 4,
        'costituzione' => 4,
    ],
    [
        'nome_carta' => 'Clessidra del Tempo',
        'costo_mana' => 3,
        'figura' => 'https://static.wikia.nocookie.net/fairytailfanon/images/1/13/Lich.jpg/revision/latest?cb=20151006140253',
        'tipo_carta' => 'Artefatto',
        'edizione' => 'Mirrodin',
        'effetti' => '3, Tap: Metti un segnalino tempo sulla Clessidra del Tempo. Gira la Clessidra del Tempo a fine turno di qualsiasi giocatore.',
        'testo' => 'Il tempo è relativo solo se hai una clessidra.',
        'forza' => 4,
        'costituzione' => 7,
    ],
    [
        'nome_carta' => 'Furia di Khalni',
        'costo_mana' => 5,
        'figura' => 'https://static.wikia.nocookie.net/forscherliga/images/5/54/Kelthuzad_TCG_KdG_21.jpg/revision/latest?cb=20100913102203',
        'tipo_carta' => 'Incantesimo',
        'edizione' => 'Zendikar',
        'effetti' => 'Sacrifica tutte le terre che controlli. La Furia di Khalni infligge danni al giocatore o al planeswalker bersaglio pari al numero di terre sacrificate in questo modo.',
        'testo' => 'La forza della natura scatena il caos sulla terra.',
        'forza' => 2,
        'costituzione' => 8,
    ],
];
